name: Application CI/CD

defaults:
  run:
    shell: bash

permissions:
  id-token: write 
  contents: read 
  pull-requests: write
  deployments: write 
  security-events: write
  actions: read
on:
  workflow_dispatch:
    inputs:
      aws-region:
        required: true
        description: "AWS Region"
      terraform-execution-iam-role-arn:
        required: false
        description: "Terraform Execution IAM Role ARN"
      eks-cluster-name:
        required: true
        description: "EKS Cluster name"
      ecr-repo-name:
        required: true
        description: "ECR REPO NAME"
  push:
    branches:
      - '**'


jobs:
  test:
    name: Run Maven Tests
    if: ${{ (github.event_name == 'push') && (github.ref != 'refs/heads/main') }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn test

  build-and-push:
    name: Run Trivy checks and Push image to ECR
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and Scan Docker Image
        id: scan
        uses: ./.github/actions/checks/

      - name: Push images to ECR
        id: build
        uses: ./.github/actions/build/
        with:
          aws-region: ${{ vars.AWS_REGION }}
          terraform-execution-iam-role-arn: ${{ secrets.AWS_IAM_ROLE_ARN }}
          ecr-repo-name: ${{ vars.ECR_REPO_NAME }}

  deploy-to-eks:
    needs: [build-and-push]
    if: github.ref == 'refs/heads/main'
    name: Deploy to EKS with Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to EKS with Helm
        id: deploy
        uses: ./.github/actions/deploy/
        with:
          aws-region:  ${{ vars.AWS_REGION }}
          terraform-execution-iam-role-arn: ${{ secrets.AWS_IAM_ROLE_ARN }}
          eks-cluster-name: ${{ vars.EKS_CLUSTER_NAME }} 
